### ISSUE TITLE
install script doesn't download latest example scripts

### ISSUE THREAD

**Issue by BryanCrotaz** [pimoroni/automation-hat#32]
Latest scripts include using the LCD on the Mini Hat. The scripts included in get.pimoroni.com/automationhat don't have these features.

**Comment by Gadgetoid** [comment]
Ah! Thank you. This will be because there has not been a release tagged that includes these scripts.

Looks like this could also explain #33 too. I'll deploy a new release that adds the dependency and examples.

**Comment by Gadgetoid** [comment]
Should be fixed as of release 0.2.3 - https://github.com/pimoroni/automation-hat/releases/tag/v0.2.3
