### ISSUE TITLE
examples/hat-mini/output.py does not run

### ISSUE THREAD

**Issue by BryanCrotaz** [pimoroni/automation-hat#33]
Downloaded this repo master as zip onto a Pi (having installed libraries as per instructions in readme)

Unzipped, then ran
`python examples/hat-mini/output.py`

Error:
```
File "output.py", line 17, in <module>
  import ST7735 as ST7735
ImportError: No module named ST7735
```

**Comment by Gadgetoid** [comment]
That's, odd. `ST7735` is a dependency of this library. However, I think you might be running into this because this library is shipped with Raspbian and `ST7735` is not.

You should be able to fix by running `sudo pip install --upgrade automationhat`

**Comment by BryanCrotaz** [comment]
I guessed at `sudo pip install st7735` and it worked.
