### ISSUE TITLE
Not an issues just a question Rasberry pi and PIM213 interface

### ISSUE THREAD

**Issue by stmark707** [pimoroni/automation-hat#34]
I am looking into this hat due to its capabilities but one of the things I am unsure about is it's way of connecting to the GPIO pins. I cannot seem to find a photo that shows how it connects to the I2C pins, voltage pins, and GPIO pins does it sit on top of the pins like some other relay boards? Can someone show me their setup? it is very important to me because this will be used in an industrial setting. Any photos or clarification on how it connects to the raspberry pi will be much appreciated and helpful.

**Comment by Gadgetoid** [comment]
Like all HATs, it plugs securely onto the Pi's main header- it uses a 40pin (2x20) socket header that connects to all 40 of the pins on the Pi.

![image](https://user-images.githubusercontent.com/1746967/87778970-f3ec9480-c823-11ea-8179-537f485b1588.png)

In situations where you need to ensure good mechanical coupling, you can also securely bolt the HAT to the Raspberry Pi through the mounting holes. As illustrated here by Cluster HAT:

![image](https://user-images.githubusercontent.com/1746967/87779334-8ab95100-c824-11ea-98d9-e61c7dd129f1.png)

I appreciate these might not illustrate exactly what you wanted to see, so I'll try to grab a low-angle photo of the Automation HAT Mini I've got set up.

**Comment by Gadgetoid** [comment]
Here’s a side-on shot of the headers connecting between HAT and Pi in my setup:

![AEA34546-29F5-4235-8A74-8350B1814A3E](https://user-images.githubusercontent.com/1746967/87779584-ea176100-c824-11ea-9e61-dab45ba2633a.jpeg)
