### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by mnelsoneorm** [pimoroni/automation-hat#4]
I've tried pip install and just downloading the git and running setup, but still a no go.  

Found the answer:  curl -sS get.pimoroni.com/automationhat | bash

Odd, I had tried that first as a guess from other Pimoroni products and the path was not found.  Maybe just network problems at the moment.

**Comment by aquafemi** [comment]
It might also help to run this as `sudo curl -sS get.pimoroni.com/automationhat | bash` to properly install the sn3218 driver needed. I had python errors like "function object has no attribute" trying to access some of the lights until I did `sudo pip install sn3218`.

**Comment by bfrosty** [comment]
Sorry: TabError: inconsistent use of tabs and spaces in indentation (ads1015.py, line 51)
during install
