### ISSUE TITLE
relay three will not toggle

### ISSUE THREAD

**Issue by kskenyon** [pimoroni/automation-hat#44]
relay.three works with the write command but it will not work with the toggle command.  I've reinstalled everything and relay three will still not respond to the toggle command.

Kevin

**Comment by Gadgetoid** [comment]
I think this was fixed in v0.4.1 - https://github.com/pimoroni/automation-hat/releases/tag/v0.4.1

**Comment by helgibbons** [comment]
Closing this one for now - let us know if you're still having problems.
